# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b22d119e7429010d70751965ffab6d5febbb763d3b10a66ab774411c9aa42471f5e0f3d55fa004380ba48acbbc6cd5fe2b608fb972285292070de26f76d82dc1

test:
  secret_key_base: 7ab3dae6ea033251e64ce63b9c659c518382c475e83809e15671d3e6a92be31ba10e10a26607be5e95366b7dd25fb111f9596d20082e224359f2d79e83e97112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
